sort:
  enabled: false

content: |-

  # Submodule power_management_services_setup

  This submodule is used to Install and configure the services DNS, NTP, NFS, SQUID on target host and sets the host as server for these services

  ## Usage
  ```
  provider "ibm" {
    region           = "sao"
    zone             = "sao01"
    ibmcloud_api_key = "your api key" != null ? "your api key" : null
  }

  module "power_management_service_squid" {

    source     = "./submodules/power_management_services_setup"
    access_host_or_ip          = var.access_host_or_ip
    target_server_ip           = var.target_server_ip
    ssh_private_key            = var.ssh_private_key
    service_config             = var.service_config
    perform_proxy_client_setup = var.perform_proxy_client_setup
  }

  ```

  <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
  ## Requirements

    | Name | Version |
    |------|---------|
    | <a name="requirement_terraform"></a> [terraform](#requirement\_terraform) | >=1.1 |
    | <a name="requirement_ibm"></a> [ibm](#requirement\_ibm) | >= 1.43.0 |

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
