sort:
  enabled: false

content: |-

  # Submodule power-cloudconnection-create

  This submodule is used to create Cloud Connections and attach the cloud connections to the Transit gateway.
  ## Usage
  ```
  provider "ibm" {
    region           = "sao"
    zone             = "sao01"
    ibmcloud_api_key = "your api key" != null ? "your api key" : null
  }

  module "cloud_connection_create" {
    source                   = "./submodules/power_cloudconnection_create"
    pvs_zone                 = var.pvs_zone
    pvs_resource_group_name  = var.pvs_resource_group_name
    pvs_service_name         = var.pvs_service_name
    transit_gateway_name     = var.transit_gateway_name
    cloud_connection_count   = var.cloud_connection_count
    cloud_connection_speed   = var.cloud_connection_speed
    cloud_connection_gr      = var.cloud_connection_gr
    cloud_connection_metered = var.cloud_connection_metered
  }
  ```

  <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
  ## Requirements

    | Name | Version |
    |------|---------|
    | <a name="requirement_terraform"></a> [terraform](#requirement\_terraform) | >=1.1 |
    | <a name="requirement_ibm"></a> [ibm](#requirement\_ibm) | >= 1.43.0 |

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
