sort:
  enabled: false

content: |-

  # Submodule power-cloudconnection-attach

  This submodule is used to attach PowerVS subnets to cloud connections

  ## Usage
  ```
  provider "ibm" {
    region           = "sao"
    zone             = "sao01"
    ibmcloud_api_key = "your api key" != null ? "your api key" : null
  }

  module "cloud_connection_attach" {
    source                  = "./submodules/power_cloudconnection_attach"
    pvs_zone                = var.pvs_zone
    pvs_resource_group_name = var.pvs_resource_group_name
    pvs_service_name        = var.pvs_service_name
    cloud_connection_count  = var.cloud_connection_count
    pvs_subnet_names        = var.pvs_subnet_names
  }
  ```

  <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
  ## Requirements

    | Name | Version |
    |------|---------|
    | <a name="requirement_terraform"></a> [terraform](#requirement\_terraform) | >=1.1 |
    | <a name="requirement_ibm"></a> [ibm](#requirement\_ibm) | >= 1.43.0 |

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
