name: All-DCs-Tests

on:
  push:
    branches: [ tests ]

  workflow_dispatch:

jobs:
  rhel-deployments-1:
    name: RHEL-Tests-1
    uses: terraform-ibm-modules/terraform-ibm-powervs-infrastructure/.github/workflows/infraTest.yml@tests
    strategy:
      fail-fast: false
      matrix:
        pvs-zones: ["tok04","osa21","sao01","tor01"]
        os: ["RHEL"]
    with:
      pvs-zone: ${{ matrix.pvs-zones }}
      os-case: ${{ matrix.os }}
      test-branch: ${{ github.event.client_payload.test_branch }}
    secrets:
      api-key: ${{ secrets.API_KEY }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      pat: ${{ secrets.PAT }}

  sles-deployments-1:
    name: SLES-Tests-1
    if: ${{ always() }}
    needs: rhel-deployments
    uses: terraform-ibm-modules/terraform-ibm-powervs-infrastructure/.github/workflows/infraTest.yml@tests
    strategy:
      fail-fast: false
      matrix:
        pvs-zones: ["tok04","osa21","sao01","tor01"]
        os: ["SLES"]
    with:
      pvs-zone: ${{ matrix.pvs-zones }}
      os-case: ${{ matrix.os }}
      test-branch: ${{ github.event.client_payload.test_branch }}
    secrets:
      api-key: ${{ secrets.API_KEY }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      pat: ${{ secrets.PAT }}
