name: All-DCs-Tests

on:
  push:
    branches: [ tests2 ]
  workflow_dispatch:

jobs:
  rhel-pre-checks:
    uses: terraform-ibm-modules/terraform-ibm-powervs-infrastructure/.github/workflows/pre-checks.yml@tests2
    with:
      locations: "osa21 sao01"
    secrets:
      api-token: ${{ secrets.API_KEY }}
      pat: ${{ secrets.PAT }}

  rhel-deployments:
    name: RHEL-Tests-1
    uses: terraform-ibm-modules/terraform-ibm-powervs-infrastructure/.github/workflows/infraTest.yml@tests2
    needs: rhel-pre-checks
    strategy:
      fail-fast: false
      matrix:
        pvs-zones: ${{fromJson(needs.rhel-pre-checks.outputs.test_locations)}}
        os: ["RHEL"]
    with:
      pvs-zone: ${{ matrix.pvs-zones }}
      os-case: ${{ matrix.os }}
      test-branch: ${{ github.event.client_payload.test_branch }}
    secrets:
      api-key: ${{ secrets.API_KEY }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      pat: ${{ secrets.PAT }}

  sles-pre-checks:
    uses: terraform-ibm-modules/terraform-ibm-powervs-infrastructure/.github/workflows/pre-checks.yml@tests2
    needs: [rhel-deployments]
    if: success() || failure()
    with:
      locations: "osa21 sao01"
    secrets:
      api-token: ${{ secrets.API_KEY }}
      pat: ${{ secrets.PAT }}

  sles-deployments:
    name: SLES-Tests-1
    needs: sles-pre-checks
    uses: terraform-ibm-modules/terraform-ibm-powervs-infrastructure/.github/workflows/infraTest.yml@tests2
    strategy:
      fail-fast: false
      matrix:
        pvs-zones: ${{fromJson(needs.sles-pre-checks.outputs.test_locations)}}
        os: ["SLES"]
    with:
      pvs-zone: ${{ matrix.pvs-zones }}
      os-case: ${{ matrix.os }}
      test-branch: ${{ github.event.client_payload.test_branch }}
    secrets:
      api-key: ${{ secrets.API_KEY }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      pat: ${{ secrets.PAT }}
