name: CI-Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-terraform-ci-pipeline:
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-terraform-module-ci.yml@v1.9.1
    secrets: inherit
    with:
      craSCCv2: true
      craTarget: "examples/ibm-catalog/deployable-architectures/full-stack"
      #craGoalIgnoreFile: "cra-tf-validate-ignore-goals.json"
      craEnvironmentVariables: "TF_VAR_prefix=full-infra,TF_VAR_powervs_zone=tok04,TF_VAR_powervs_resource_group_name=Default,TF_VAR_ssh_private_key=${{ secrets.CRA_SSH_PRIVATE_KEY }},TF_VAR_preset=${{ secrets.CRA_PRESET_EOF }},TF_VAR_ssh_public_key=${{ secrets.CRA_SSH_PUBLIC_KEY }}"
