name: Do things every 5 minutes
on:
  schedule:
    - cron: "0 0 * * *"
  branches:
      - main

jobs:
  run_terraform:
    name: Plan/Run terraform
    env:
      IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.7

      - name: Initialize Terraform
        run: |
          cd ./examples/standard
          terraform init -input=false

      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: |
          cd ./examples/standard
          terraform plan \
             -input=false -no-color -out=tfplan \
             -var-file ../../.github/test_configs/dal12_input.tfvars \
             -var ssh_public_key=$SSH_PUBLIC_KEY \
             -var ssh_private_key=$SSH_PRIVATE_KEY \
             -var ibmcloud_api_key=$IBM_CLOUD_API_KEY \
             && terraform show -no-color tfplan

#      - name: Apply Terraform
#        if: steps.plan.outcome == 'success'
#        id: apply
#        continue-on-error: true
#        run: |
#          cd ./examples/standard
#          terraform apply \
#             -input=false -no-color \
#             tfplan
#
#      - name: Destroy Terraform
#        if: steps.plan.outcome == 'success'
#        id: destroy
#        continue-on-error: true
#        run: |
#          cd ./examples/standard
#          terraform destroy \
#            -input=false \
#            -no-color \
#            tfplan
