name: All-DCs-Tests

on:
  push:
    branches: [ tests ]
  workflow_dispatch:

jobs:
  skipper:
    name: Test Location Selection
    runs-on: ubuntu-latest
    container:
      image: icr.io/goldeneye_images/goldeneye-ci-image:stable
      env:
        NO_CONTAINER: "false"
        API_KEY: ${{ secrets.API_KEY }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.head_ref }}
      - name: Script Run
        run: |
          ibmcloud plugin install catalogs-management
          ibmcloud plugin install schematics
          ibmcloud plugin install dl-cli
          echo ${{ github.head_ref }}
          chmod -R +rwx test-assets
          bash test-assets/scripts/find_testable_locations.sh
          echo >> $GITHUB_OUTPUT
        #source testlocations.env
        #TESTABLE_LOCATIONS="\"${TESTABLE_LOCATIONS//,/\",\"}\""


  #example_matrix:
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      version: ${{ github.event.client_payload.versions }}
  #  steps:
  #    - uses: actions/setup-node@v3
  #      with:
  #        node-version: ${{ matrix.version }}
