sort:
  enabled: false

content: |-

  # Submodule initial-validation

  This submodule check whether the variables for cloud connections reuse and transit gateway name are provided

  ## Usage
  ```
  provider "ibm" {
    region           = "sao"
    zone             = "sao01"
    ibmcloud_api_key = "your api key" != null ? "your api key" : null
  }

  module "initial_validation" {
  source = "./submodules/initial_validation"
  cloud_connection_validate = var.cloud_connection_validate
  }

  ```

  ## Requirements

    | Name | Version |
    |------|---------|
    | <a name="requirement_terraform"></a> [terraform](#requirement\_terraform) | >=1.1 |
    | <a name="requirement_ibm"></a> [ibm](#requirement\_ibm) | >= 1.43.0 |

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
